In [5]:
import yfinance as yf
import pandas as pd
import streamlit as st
from pandas.tseries.offsets import DateOffset

In [6]:
tickers = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0].Symbol

In [8]:
tickers = tickers.to_list()

In [13]:
@st.cache_data
def getdata():
    df = yf.download(tickers,start='2020-01-01')
    df = df['Close']
    return df

2024-02-16 14:15:22.788 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [14]:
df = getdata()

2024-02-16 14:44:00.558
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\ASHISH SINHA\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2024-02-16 14:44:00.558 No runtime found, using MemoryCacheStorageManager
[*********************100%%**********************]  503 of 503 completed

2 Failed downloads:
['BRK.B']: Exception('%ticker%: No timezone found, symbol may be delisted')
['BF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2020-01-01 -> 2024-02-16)')

In [15]:
st.title('Index component performance of the S&P500')

DeltaGenerator()

In [16]:
n = st.number_input('Please provide the performance horizon in months:', min_value=1, max_value=24)

In [17]:
df

Ticker,A,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,...,WYNN,XEL,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,85.949997,29.090000,75.087502,89.550003,NaN,86.949997,43.400002,210.149994,334.429993,120.430000,...,143.600006,62.380001,70.900002,56.930000,79.849998,102.169998,144.854370,259.140015,52.439999,134.139999
2020-01-03,84.570000,27.650000,74.357498,88.699997,NaN,85.889999,43.349998,209.800003,331.809998,118.309998,...,141.470001,62.680000,70.330002,56.299999,80.320000,101.849998,144.475723,256.049988,51.700001,134.160004
2020-01-06,84.820000,27.320000,74.949997,89.400002,NaN,86.339996,43.520000,208.429993,333.709991,116.919998,...,141.190002,62.590000,70.870003,56.610001,79.800003,101.790001,143.640778,258.010010,51.070000,133.130005
2020-01-07,85.080002,27.219999,74.597504,88.889999,NaN,85.860001,43.160000,203.929993,333.390015,119.580002,...,141.860001,62.459999,70.290001,56.910000,79.500000,101.970001,143.514557,256.470001,50.759998,133.580002
2020-01-08,85.919998,27.840000,75.797501,89.519997,NaN,86.209999,42.730000,204.330002,337.869995,120.660004,...,142.750000,62.400002,69.230003,57.509998,79.769997,102.150002,145.233017,247.639999,51.259998,133.289993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-02-09,133.339996,14.880000,188.850006,174.080002,147.595001,111.809998,83.459999,371.670013,627.210022,195.020004,...,105.599998,58.169998,101.769997,32.790001,124.300003,130.270004,122.800003,253.089996,40.090000,197.320007
2024-02-12,132.309998,14.930000,187.149994,173.070007,153.800003,112.529999,83.099998,367.429993,611.840027,194.050003,...,105.720001,58.970001,103.169998,33.520000,123.300003,131.360001,125.849998,259.399994,41.240002,196.690002
2024-02-13,129.759995,14.610000,185.039993,173.289993,150.820007,111.339996,84.059998,362.809998,601.890015,184.690002,...,104.199997,58.279999,101.339996,32.450001,121.730003,131.210007,123.160004,245.800003,39.340000,183.490005
2024-02-14,132.240005,14.860000,184.149994,174.419998,148.199997,112.059998,84.870003,370.980011,604.659973,186.320007,...,105.209999,58.680000,100.839996,32.669998,124.160004,134.009995,121.839996,252.960007,40.419998,184.080002
2024-02-15,134.750000,14.900000,183.860001,176.589996,157.690002,113.639999,87.400002,371.510010,590.440002,187.539993,...,105.730003,59.009998,103.730003,33.860001,124.419998,135.399994,124.400002,283.750000,41.520000,189.649994

In [24]:
df[:df.index[-1] - DateOffset(months=1)].tail(1).squeeze()

Ticker
A       130.539993
AAL      13.210000
AAPL    185.919998
ABBV    162.399994
ABNB    137.139999
           ...
YUM     129.130005
ZBH     123.070000
ZBRA    248.869995
ZION     42.110001
ZTS     198.940002
Name: 2024-01-12 00:00:00, Length: 503, dtype: float64

In [26]:
df.loc[df.index[-1]]

Ticker
A       134.750000
AAL      14.900000
AAPL    183.860001
ABBV    176.589996
ABNB    157.690002
           ...
YUM     135.399994
ZBH     124.400002
ZBRA    283.750000
ZION     41.520000
ZTS     189.649994
Name: 2024-02-15 00:00:00, Length: 503, dtype: float64

In [27]:
def get_ret(df,n):
    previous_prices = df[:df.index[-1] - DateOffset(months=n)].tail(1).squeeze()
    recent_prices = df.loc[df.index[-1]]
    ret_df = recent_prices/previous_prices -1
    return previous_prices.name, ret_df

In [40]:
date, ret_df = get_ret(df,n)

In [33]:
winners,losers = ret_df.nlargest(10), ret_df.nsmallest(10)

In [36]:
winners.name,losers.name = 'winners','losers'

In [37]:
st.table(winners)
st.table(losers)

DeltaGenerator()

In [39]:
winnerpick = st.selectbox('Pick a winner to visualize:',winners.index)
st.line_chart(df[winnerpick][date:])

loserpick = st.selectbox('Pick a loser to visualize:',winners.index)
st.line_chart(df[loserpick][date:])

DeltaGenerator()